// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uxmbszinqmqpkxsibblo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV4bWJzemlucW1xcGt4c2liYmxvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMyNjU3MjYsImV4cCI6MjA1ODg0MTcyNn0.onDSWfwhKyN6rrQBOuIZkRUB8-Dnm3YAvKHYw5y6jHA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);